// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_nasa_apod/test/src/features/apod/presentation/widgets/favorite_item_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bloc/bloc.dart' as _i6;
import 'package:flutter_nasa_apod/src/features/apod/domain/usecases/get_apod_by_date.dart'
    as _i2;
import 'package:flutter_nasa_apod/src/features/apod/domain/usecases/manage_favorites.dart'
    as _i3;
import 'package:flutter_nasa_apod/src/features/apod/presentation/bloc/apod/apod_bloc.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetApodByDate_0 extends _i1.SmartFake implements _i2.GetApodByDate {
  _FakeGetApodByDate_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetFavorites_1 extends _i1.SmartFake implements _i3.GetFavorites {
  _FakeGetFavorites_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveFavorite_2 extends _i1.SmartFake implements _i3.SaveFavorite {
  _FakeSaveFavorite_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveFavorite_3 extends _i1.SmartFake
    implements _i3.RemoveFavorite {
  _FakeRemoveFavorite_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApodState_4 extends _i1.SmartFake implements _i4.ApodState {
  _FakeApodState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApodBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodBloc extends _i1.Mock implements _i4.ApodBloc {
  MockApodBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetApodByDate get getApodByDate => (super.noSuchMethod(
        Invocation.getter(#getApodByDate),
        returnValue: _FakeGetApodByDate_0(
          this,
          Invocation.getter(#getApodByDate),
        ),
      ) as _i2.GetApodByDate);

  @override
  _i3.GetFavorites get getFavorites => (super.noSuchMethod(
        Invocation.getter(#getFavorites),
        returnValue: _FakeGetFavorites_1(
          this,
          Invocation.getter(#getFavorites),
        ),
      ) as _i3.GetFavorites);

  @override
  _i3.SaveFavorite get saveFavorite => (super.noSuchMethod(
        Invocation.getter(#saveFavorite),
        returnValue: _FakeSaveFavorite_2(
          this,
          Invocation.getter(#saveFavorite),
        ),
      ) as _i3.SaveFavorite);

  @override
  _i3.RemoveFavorite get removeFavorite => (super.noSuchMethod(
        Invocation.getter(#removeFavorite),
        returnValue: _FakeRemoveFavorite_3(
          this,
          Invocation.getter(#removeFavorite),
        ),
      ) as _i3.RemoveFavorite);

  @override
  _i4.ApodState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeApodState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.ApodState);

  @override
  _i5.Stream<_i4.ApodState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i4.ApodState>.empty(),
      ) as _i5.Stream<_i4.ApodState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i4.ApodEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i4.ApodEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.ApodState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i4.ApodEvent>(
    _i6.EventHandler<E, _i4.ApodState>? handler, {
    _i6.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i6.Transition<_i4.ApodEvent, _i4.ApodState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onChange(_i6.Change<_i4.ApodState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
